{
 "title": "INSARAMA_DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Company_Role",
    "query": "SELECT DISTINCT company_role FROM \"COMPANIES\""
   }
  ]
 },
 "panels": [
  {
   "title": "Video Game Rating / (Genre-Platform)",
   "type": "barchart",
   "description": "Study of average video game rating per Genre and Game Platform",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "MediaReviewsDB",
     "rawSql": "SELECT g.genre_title || ' - ' || s.section_name AS Genre_Platform, AVG(rating) as avg_rating\r\nFROM \"FACT_REVIEWS\" as fr\r\nJOIN \"DIM_SECTION\" as s ON s.id = fr.section_id\r\nJOIN \"DIM_MEDIA_INFO\" as mi ON fr.media_info_id = mi.id\r\nJOIN \"BRIDGE_MEDIA_GENRE\" as bmg ON mi.id = bmg.media_id\r\nJOIN \"GENRES\" as g ON bmg.genre_id = g.id\r\nWHERE s.section_type NOT IN ('Season', 'Display')\r\nGROUP BY Genre_Platform\r\nORDER BY avg_rating DESC"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 48, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "MediaReviewsDB",
     "rawSql": "SELECT c.company_name as Company, AVG(rating) as avg_rating\r\nFROM \"FACT_REVIEWS\" as fr\r\nJOIN \"DIM_MEDIA_INFO\" as mi ON fr.media_info_id = mi.id\r\nJOIN \"BRIDGE_MEDIA_COMPANY\" as bmc ON mi.id = bmc.media_id\r\nJOIN \"COMPANIES\" as c ON bmc.company_id = c.id\r\nWHERE c.company_role IN ($Company_Role)\r\nGROUP BY Company\r\nORDER BY avg_rating DESC"
    }
   ]
  },
  {
   "title": "Average Rating per year for user",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 29 },
   "targets": [
    {
     "dataset": "MediaReviewsDB",
     "rawSql": "SELECT \r\n  d.year AS \"Année\",\r\n  ROUND(AVG(f.rating)::numeric, 2) AS \"Note Moyenne\" \r\nFROM \"FACT_REVIEWS\" AS f\r\nJOIN \"DIM_TIME\" AS d ON f.time_id = d.id \r\nJOIN \"DIM_REVIEWER\" AS r ON f.reviewer_id = r.id\r\nWHERE r.is_critic = false \r\n  AND d.year IS NOT NULL \r\nGROUP BY d.year\r\nORDER BY d.year ASC;"
    }
   ]
  },
  {
   "title": "Average Rating per year for critics",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 43 },
   "targets": [
    {
     "dataset": "MediaReviewsDB",
     "rawSql": "SELECT \r\n  d.year AS \"Année\",\r\n  ROUND(AVG(f.rating)::numeric, 2) AS \"Note Moyenne\" \r\nFROM \"FACT_REVIEWS\" AS f\r\nJOIN \"DIM_TIME\" AS d ON f.time_id = d.id \r\nJOIN \"DIM_REVIEWER\" AS r ON f.reviewer_id = r.id\r\nWHERE r.is_critic = true \r\n  AND d.year IS NOT NULL \r\nGROUP BY d.year\r\nORDER BY d.year ASC;"
    }
   ]
  },
  {
   "title": "Avg Rating of Media Involving Michaels as cast",
   "type": "bargauge",
   "description": "We found it funny.",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 57 },
   "targets": [
    {
     "dataset": "MediaReviewsDB",
     "rawSql": "SELECT mi.primary_title, AVG(fr.rating) as avg_rating \r\nFROM \"FACT_REVIEWS\" as fr\r\nJOIN \"DIM_MEDIA_INFO\" mi ON fr.media_info_id = mi.id\r\nJOIN \"BRIDGE_MEDIA_ROLE\" bmr ON mi.id = bmr.media_id\r\nJOIN \"ROLES\" r ON bmr.role_id = r.id\r\nWHERE r.role LIKE '%Michael%' or r.person_name LIKE '%Michael%'\r\nGROUP BY primary_title\r\nORDER BY avg_rating"
    }
   ]
  },
  {
   "title": "Best Rated Genres per Company",
   "type": "table",
   "description": "Score calculated by the sum of ratings*implication on film (weight)",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 68 },
   "targets": [
    {
     "dataset": "MediaReviewsDB",
     "rawSql": "WITH company_genre_scores AS (\r\n    SELECT \r\n        c.company_name AS Company,\r\n        g.genre_title AS Genre,\r\n        SUM(fr.rating * bmg.weight) AS weighted_score\r\n    FROM \"FACT_REVIEWS\" as fr\r\n    JOIN \"DIM_MEDIA_INFO\" as mi ON fr.media_info_id = mi.id\r\n    JOIN \"BRIDGE_MEDIA_GENRE\" as bmg ON mi.id = bmg.media_id\r\n    JOIN \"GENRES\" as g ON bmg.genre_id = g.id\r\n    JOIN \"BRIDGE_MEDIA_COMPANY\" as bmc ON mi.id = bmc.media_id\r\n    JOIN \"COMPANIES\" as c ON bmc.company_id = c.id\r\n    GROUP BY c.company_name, g.genre_title\r\n)\r\nSELECT company as Company, genre as Best_Rated_Genre\r\nFROM (\r\n    SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY company ORDER BY weighted_score DESC) as rn\r\n    FROM company_genre_scores\r\n) t\r\nWHERE rn = 1;"
    }
   ]
  }
 ]
}